//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThScoreFileConverter.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CharacterNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CharacterNames() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThScoreFileConverter.Core.Resources.CharacterNames", typeof(CharacterNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Alice に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Alice {
            get {
                return ResourceManager.GetString("Alice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alice Margatroid に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AliceFullName {
            get {
                return ResourceManager.GetString("AliceFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aun に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Aun {
            get {
                return ResourceManager.GetString("Aun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Komano Aun に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AunFullName {
            get {
                return ResourceManager.GetString("AunFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aya に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Aya {
            get {
                return ResourceManager.GetString("Aya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shameimaru Aya に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AyaFullName {
            get {
                return ResourceManager.GetString("AyaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Benben に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Benben {
            get {
                return ResourceManager.GetString("Benben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tsukumo Benben に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BenbenFullName {
            get {
                return ResourceManager.GetString("BenbenFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Biten に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Biten {
            get {
                return ResourceManager.GetString("Biten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Son Biten に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BitenFullName {
            get {
                return ResourceManager.GetString("BitenFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Byakuren に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Byakuren {
            get {
                return ResourceManager.GetString("Byakuren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hijiri Byakuren に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ByakurenFullName {
            get {
                return ResourceManager.GetString("ByakurenFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Catfish に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Catfish {
            get {
                return ResourceManager.GetString("Catfish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giant Catfish に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CatfishFullName {
            get {
                return ResourceManager.GetString("CatfishFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Chen {
            get {
                return ResourceManager.GetString("Chen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChenFullName {
            get {
                return ResourceManager.GetString("ChenFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chimata に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Chimata {
            get {
                return ResourceManager.GetString("Chimata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tenkyuu Chimata に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChimataFullName {
            get {
                return ResourceManager.GetString("ChimataFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chiyari に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Chiyari {
            get {
                return ResourceManager.GetString("Chiyari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tenkajin Chiyari に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChiyariFullName {
            get {
                return ResourceManager.GetString("ChiyariFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cirno に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cirno {
            get {
                return ResourceManager.GetString("Cirno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cirno に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CirnoFullName {
            get {
                return ResourceManager.GetString("CirnoFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clownpiece に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Clownpiece {
            get {
                return ResourceManager.GetString("Clownpiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clownpiece に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClownpieceFullName {
            get {
                return ResourceManager.GetString("ClownpieceFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Daiyousei に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Daiyousei {
            get {
                return ResourceManager.GetString("Daiyousei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Daiyousei に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DaiyouseiFullName {
            get {
                return ResourceManager.GetString("DaiyouseiFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doremy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Doremy {
            get {
                return ResourceManager.GetString("Doremy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doremy Sweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoremyFullName {
            get {
                return ResourceManager.GetString("DoremyFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sumireko (Dream) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DreamSumireko {
            get {
                return ResourceManager.GetString("DreamSumireko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Usami Sumireko (Dream) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DreamSumirekoFullName {
            get {
                return ResourceManager.GetString("DreamSumirekoFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eika に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Eika {
            get {
                return ResourceManager.GetString("Eika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ebisu Eika に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EikaFullName {
            get {
                return ResourceManager.GetString("EikaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eiki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Eiki {
            get {
                return ResourceManager.GetString("Eiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shiki Eiki, Yamaxanadu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EikiFullName {
            get {
                return ResourceManager.GetString("EikiFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eirin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Eirin {
            get {
                return ResourceManager.GetString("Eirin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yagokoro Eirin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EirinFullName {
            get {
                return ResourceManager.GetString("EirinFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enoko に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Enoko {
            get {
                return ResourceManager.GetString("Enoko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mitsugashira Enoko に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnokoFullName {
            get {
                return ResourceManager.GetString("EnokoFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flandre に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Flandre {
            get {
                return ResourceManager.GetString("Flandre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flandre Scarlet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FlandreFullName {
            get {
                return ResourceManager.GetString("FlandreFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Futo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Futo {
            get {
                return ResourceManager.GetString("Futo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mononobe no Futo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FutoFullName {
            get {
                return ResourceManager.GetString("FutoFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hatate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Hatate {
            get {
                return ResourceManager.GetString("Hatate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Himekaidou Hatate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HatateFullName {
            get {
                return ResourceManager.GetString("HatateFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hecatia に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Hecatia {
            get {
                return ResourceManager.GetString("Hecatia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hecatia Lapislazuli に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HecatiaFullName {
            get {
                return ResourceManager.GetString("HecatiaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hina に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Hina {
            get {
                return ResourceManager.GetString("Hina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kagiyama Hina に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HinaFullName {
            get {
                return ResourceManager.GetString("HinaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hisami に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Hisami {
            get {
                return ResourceManager.GetString("Hisami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yomotsu Hisami に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HisamiFullName {
            get {
                return ResourceManager.GetString("HisamiFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ichirin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ichirin {
            get {
                return ResourceManager.GetString("Ichirin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kumoi Ichirin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IchirinFullName {
            get {
                return ResourceManager.GetString("IchirinFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Iku に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Iku {
            get {
                return ResourceManager.GetString("Iku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nagae Iku に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IkuFullName {
            get {
                return ResourceManager.GetString("IkuFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Joon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Joon {
            get {
                return ResourceManager.GetString("Joon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yorigami Joon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JoonFullName {
            get {
                return ResourceManager.GetString("JoonFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Junko に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Junko {
            get {
                return ResourceManager.GetString("Junko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Junko に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JunkoFullName {
            get {
                return ResourceManager.GetString("JunkoFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kagerou に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Kagerou {
            get {
                return ResourceManager.GetString("Kagerou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Imaizumi Kagerou に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KagerouFullName {
            get {
                return ResourceManager.GetString("KagerouFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaguya に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Kaguya {
            get {
                return ResourceManager.GetString("Kaguya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Houraisan Kaguya に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KaguyaFullName {
            get {
                return ResourceManager.GetString("KaguyaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kanako に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Kanako {
            get {
                return ResourceManager.GetString("Kanako", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yasaka Kanako に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KanakoFullName {
            get {
                return ResourceManager.GetString("KanakoFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kasen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Kasen {
            get {
                return ResourceManager.GetString("Kasen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ibaraki Kasen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KasenFullName {
            get {
                return ResourceManager.GetString("KasenFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keiki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Keiki {
            get {
                return ResourceManager.GetString("Keiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Haniyasushin Keiki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeikiFullName {
            get {
                return ResourceManager.GetString("KeikiFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keine に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Keine {
            get {
                return ResourceManager.GetString("Keine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kamishirasawa Keine に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeineFullName {
            get {
                return ResourceManager.GetString("KeineFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kisume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Kisume {
            get {
                return ResourceManager.GetString("Kisume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kisume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KisumeFullName {
            get {
                return ResourceManager.GetString("KisumeFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Koakuma に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Koakuma {
            get {
                return ResourceManager.GetString("Koakuma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Koakuma に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KoakumaFullName {
            get {
                return ResourceManager.GetString("KoakumaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kogasa に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Kogasa {
            get {
                return ResourceManager.GetString("Kogasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tatara Kogasa に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KogasaFullName {
            get {
                return ResourceManager.GetString("KogasaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Koishi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Koishi {
            get {
                return ResourceManager.GetString("Koishi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Komeiji Koishi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KoishiFullName {
            get {
                return ResourceManager.GetString("KoishiFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kokoro に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Kokoro {
            get {
                return ResourceManager.GetString("Kokoro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hata no Kokoro に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KokoroFullName {
            get {
                return ResourceManager.GetString("KokoroFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Komachi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Komachi {
            get {
                return ResourceManager.GetString("Komachi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Onozuka Komachi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KomachiFullName {
            get {
                return ResourceManager.GetString("KomachiFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kutaka に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Kutaka {
            get {
                return ResourceManager.GetString("Kutaka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Niwatari Kutaka に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KutakaFullName {
            get {
                return ResourceManager.GetString("KutakaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kyouko に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Kyouko {
            get {
                return ResourceManager.GetString("Kyouko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kasodani Kyouko に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KyoukoFullName {
            get {
                return ResourceManager.GetString("KyoukoFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Larva に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Larva {
            get {
                return ResourceManager.GetString("Larva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eternity Larva に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LarvaFullName {
            get {
                return ResourceManager.GetString("LarvaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Letty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Letty {
            get {
                return ResourceManager.GetString("Letty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Letty Whiterock に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LettyFullName {
            get {
                return ResourceManager.GetString("LettyFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lily に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Lily {
            get {
                return ResourceManager.GetString("Lily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lily White に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LilyFullName {
            get {
                return ResourceManager.GetString("LilyFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Luna に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Luna {
            get {
                return ResourceManager.GetString("Luna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Luna Child に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LunaFullName {
            get {
                return ResourceManager.GetString("LunaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lunasa に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Lunasa {
            get {
                return ResourceManager.GetString("Lunasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lunasa Prismriver に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LunasaFullName {
            get {
                return ResourceManager.GetString("LunasaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lyrica に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Lyrica {
            get {
                return ResourceManager.GetString("Lyrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lyrica Prismriver に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LyricaFullName {
            get {
                return ResourceManager.GetString("LyricaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mai に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mai {
            get {
                return ResourceManager.GetString("Mai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teireida Mai に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MaiFullName {
            get {
                return ResourceManager.GetString("MaiFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mamizou に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mamizou {
            get {
                return ResourceManager.GetString("Mamizou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Futatsuiwa Mamizou に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MamizouFullName {
            get {
                return ResourceManager.GetString("MamizouFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Marisa に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Marisa {
            get {
                return ResourceManager.GetString("Marisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kirisame Marisa に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MarisaFullName {
            get {
                return ResourceManager.GetString("MarisaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mayumi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mayumi {
            get {
                return ResourceManager.GetString("Mayumi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Joutouguu Mayumi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MayumiFullName {
            get {
                return ResourceManager.GetString("MayumiFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Medicine に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Medicine {
            get {
                return ResourceManager.GetString("Medicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Medicine Melancholy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MedicineFullName {
            get {
                return ResourceManager.GetString("MedicineFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Megumu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Megumu {
            get {
                return ResourceManager.GetString("Megumu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IIzunamaru Megumu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MegumuFullName {
            get {
                return ResourceManager.GetString("MegumuFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Meiling に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Meiling {
            get {
                return ResourceManager.GetString("Meiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hong Meiling に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MeilingFullName {
            get {
                return ResourceManager.GetString("MeilingFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merlin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Merlin {
            get {
                return ResourceManager.GetString("Merlin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merlin Prismriver に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MerlinFullName {
            get {
                return ResourceManager.GetString("MerlinFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mike に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mike {
            get {
                return ResourceManager.GetString("Mike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Goutokuji Mike に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MikeFullName {
            get {
                return ResourceManager.GetString("MikeFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Miko に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Miko {
            get {
                return ResourceManager.GetString("Miko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toyosatomimi no Miko に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MikoFullName {
            get {
                return ResourceManager.GetString("MikoFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minamitsu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Minamitsu {
            get {
                return ResourceManager.GetString("Minamitsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Murasa Minamitsu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MinamitsuFullName {
            get {
                return ResourceManager.GetString("MinamitsuFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minoriko に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Minoriko {
            get {
                return ResourceManager.GetString("Minoriko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aki Minoriko に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MinorikoFullName {
            get {
                return ResourceManager.GetString("MinorikoFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Misumaru に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Misumaru {
            get {
                return ResourceManager.GetString("Misumaru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tamatsukuri Misumaru に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MisumaruFullName {
            get {
                return ResourceManager.GetString("MisumaruFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mokou に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mokou {
            get {
                return ResourceManager.GetString("Mokou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fujiwara no Mokou に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MokouFullName {
            get {
                return ResourceManager.GetString("MokouFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Momiji に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Momiji {
            get {
                return ResourceManager.GetString("Momiji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inubashiri Momiji に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MomijiFullName {
            get {
                return ResourceManager.GetString("MomijiFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Momoyo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Momoyo {
            get {
                return ResourceManager.GetString("Momoyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Himemushi Momoyo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MomoyoFullName {
            get {
                return ResourceManager.GetString("MomoyoFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mystia に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mystia {
            get {
                return ResourceManager.GetString("Mystia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mystia Lorelei に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MystiaFullName {
            get {
                return ResourceManager.GetString("MystiaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Narumi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Narumi {
            get {
                return ResourceManager.GetString("Narumi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yatadera Narumi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NarumiFullName {
            get {
                return ResourceManager.GetString("NarumiFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nazrin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Nazrin {
            get {
                return ResourceManager.GetString("Nazrin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nazrin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NazrinFullName {
            get {
                return ResourceManager.GetString("NazrinFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nemuno に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Nemuno {
            get {
                return ResourceManager.GetString("Nemuno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sakata Nemuno に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NemunoFullName {
            get {
                return ResourceManager.GetString("NemunoFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nitori に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Nitori {
            get {
                return ResourceManager.GetString("Nitori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kawashiro Nitori に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NitoriFullName {
            get {
                return ResourceManager.GetString("NitoriFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Nue {
            get {
                return ResourceManager.GetString("Nue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Houjuu Nue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NueFullName {
            get {
                return ResourceManager.GetString("NueFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Okina に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Okina {
            get {
                return ResourceManager.GetString("Okina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Matara Okina に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OkinaFullName {
            get {
                return ResourceManager.GetString("OkinaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parsee に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Parsee {
            get {
                return ResourceManager.GetString("Parsee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mizuhashi Parsee に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParseeFullName {
            get {
                return ResourceManager.GetString("ParseeFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Patchouli に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Patchouli {
            get {
                return ResourceManager.GetString("Patchouli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Patchouli Knowledge に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PatchouliFullName {
            get {
                return ResourceManager.GetString("PatchouliFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Raiko に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Raiko {
            get {
                return ResourceManager.GetString("Raiko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Horikawa Raiko に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RaikoFullName {
            get {
                return ResourceManager.GetString("RaikoFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ran に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ran {
            get {
                return ResourceManager.GetString("Ran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yakumo Ran に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RanFullName {
            get {
                return ResourceManager.GetString("RanFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reimu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Reimu {
            get {
                return ResourceManager.GetString("Reimu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hakurei Reimu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReimuFullName {
            get {
                return ResourceManager.GetString("ReimuFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reisen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Reisen {
            get {
                return ResourceManager.GetString("Reisen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reisen Udongein Inaba に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReisenFullName {
            get {
                return ResourceManager.GetString("ReisenFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remilia に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Remilia {
            get {
                return ResourceManager.GetString("Remilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remilia Scarlet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemiliaFullName {
            get {
                return ResourceManager.GetString("RemiliaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rin {
            get {
                return ResourceManager.GetString("Rin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaenbyou Rin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RinFullName {
            get {
                return ResourceManager.GetString("RinFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ringo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ringo {
            get {
                return ResourceManager.GetString("Ringo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ringo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RingoFullName {
            get {
                return ResourceManager.GetString("RingoFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rumia に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Rumia {
            get {
                return ResourceManager.GetString("Rumia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rumia に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RumiaFullName {
            get {
                return ResourceManager.GetString("RumiaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sagume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sagume {
            get {
                return ResourceManager.GetString("Sagume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kishin Sagume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SagumeFullName {
            get {
                return ResourceManager.GetString("SagumeFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Saki {
            get {
                return ResourceManager.GetString("Saki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kurokoma Saki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SakiFullName {
            get {
                return ResourceManager.GetString("SakiFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sakuya に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sakuya {
            get {
                return ResourceManager.GetString("Sakuya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Izayoi Sakuya に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SakuyaFullName {
            get {
                return ResourceManager.GetString("SakuyaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sanae に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sanae {
            get {
                return ResourceManager.GetString("Sanae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kochiya Sanae に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SanaeFullName {
            get {
                return ResourceManager.GetString("SanaeFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sannyo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sannyo {
            get {
                return ResourceManager.GetString("Sannyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Komakusa Sannyo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SannyoFullName {
            get {
                return ResourceManager.GetString("SannyoFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Satono に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Satono {
            get {
                return ResourceManager.GetString("Satono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nishida Satono に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SatonoFullName {
            get {
                return ResourceManager.GetString("SatonoFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Satori に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Satori {
            get {
                return ResourceManager.GetString("Satori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Komeiji Satori に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SatoriFullName {
            get {
                return ResourceManager.GetString("SatoriFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seiga に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seiga {
            get {
                return ResourceManager.GetString("Seiga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaku Seiga に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SeigaFullName {
            get {
                return ResourceManager.GetString("SeigaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seija に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seija {
            get {
                return ResourceManager.GetString("Seija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kijin Seija に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SeijaFullName {
            get {
                return ResourceManager.GetString("SeijaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seiran に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Seiran {
            get {
                return ResourceManager.GetString("Seiran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seiran に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SeiranFullName {
            get {
                return ResourceManager.GetString("SeiranFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sekibanki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sekibanki {
            get {
                return ResourceManager.GetString("Sekibanki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sekibanki に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SekibankiFullName {
            get {
                return ResourceManager.GetString("SekibankiFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shinmyoumaru に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shinmyoumaru {
            get {
                return ResourceManager.GetString("Shinmyoumaru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sukuna Shinmyoumaru に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShinmyoumaruFullName {
            get {
                return ResourceManager.GetString("ShinmyoumaruFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shion {
            get {
                return ResourceManager.GetString("Shion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yorigami Shion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShionFullName {
            get {
                return ResourceManager.GetString("ShionFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shizuha に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shizuha {
            get {
                return ResourceManager.GetString("Shizuha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aki Shizuha に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShizuhaFullName {
            get {
                return ResourceManager.GetString("ShizuhaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shou に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Shou {
            get {
                return ResourceManager.GetString("Shou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toramaru Shou に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShouFullName {
            get {
                return ResourceManager.GetString("ShouFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Star に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Star {
            get {
                return ResourceManager.GetString("Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Star Sapphire に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StarFullName {
            get {
                return ResourceManager.GetString("StarFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Suika に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Suika {
            get {
                return ResourceManager.GetString("Suika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ibuki Suika に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SuikaFullName {
            get {
                return ResourceManager.GetString("SuikaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sumireko に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sumireko {
            get {
                return ResourceManager.GetString("Sumireko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Usami Sumireko に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SumirekoFullName {
            get {
                return ResourceManager.GetString("SumirekoFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sunny に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sunny {
            get {
                return ResourceManager.GetString("Sunny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sunny Milk に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SunnyFullName {
            get {
                return ResourceManager.GetString("SunnyFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Suwako に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Suwako {
            get {
                return ResourceManager.GetString("Suwako", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moriya Suwako に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SuwakoFullName {
            get {
                return ResourceManager.GetString("SuwakoFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Takane に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Takane {
            get {
                return ResourceManager.GetString("Takane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yamashiro Takane に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TakaneFullName {
            get {
                return ResourceManager.GetString("TakaneFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tenshi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tenshi {
            get {
                return ResourceManager.GetString("Tenshi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hinanawi Tenshi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TenshiFullName {
            get {
                return ResourceManager.GetString("TenshiFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tewi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tewi {
            get {
                return ResourceManager.GetString("Tewi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inaba Tewi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TewiFullName {
            get {
                return ResourceManager.GetString("TewiFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tojiko に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tojiko {
            get {
                return ResourceManager.GetString("Tojiko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Soga no Tojiko に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TojikoFullName {
            get {
                return ResourceManager.GetString("TojikoFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tsukasa に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tsukasa {
            get {
                return ResourceManager.GetString("Tsukasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kudamaki Tsukasa に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TsukasaFullName {
            get {
                return ResourceManager.GetString("TsukasaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unzan に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Unzan {
            get {
                return ResourceManager.GetString("Unzan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unzan に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnzanFullName {
            get {
                return ResourceManager.GetString("UnzanFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Urumi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Urumi {
            get {
                return ResourceManager.GetString("Urumi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ushizaki Urumi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UrumiFullName {
            get {
                return ResourceManager.GetString("UrumiFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Utsuho に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Utsuho {
            get {
                return ResourceManager.GetString("Utsuho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reiuji Utsuho に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UtsuhoFullName {
            get {
                return ResourceManager.GetString("UtsuhoFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wakasagihime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Wakasagihime {
            get {
                return ResourceManager.GetString("Wakasagihime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wakasagihime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WakasagihimeFullName {
            get {
                return ResourceManager.GetString("WakasagihimeFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wriggle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Wriggle {
            get {
                return ResourceManager.GetString("Wriggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wriggle Nightbug に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WriggleFullName {
            get {
                return ResourceManager.GetString("WriggleFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yachie に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Yachie {
            get {
                return ResourceManager.GetString("Yachie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kicchou Yachie に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string YachieFullName {
            get {
                return ResourceManager.GetString("YachieFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yamame に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Yamame {
            get {
                return ResourceManager.GetString("Yamame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kurodani Yamame に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string YamameFullName {
            get {
                return ResourceManager.GetString("YamameFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yatsuhashi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Yatsuhashi {
            get {
                return ResourceManager.GetString("Yatsuhashi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tsukumo Yatsuhashi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string YatsuhashiFullName {
            get {
                return ResourceManager.GetString("YatsuhashiFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yoshika に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Yoshika {
            get {
                return ResourceManager.GetString("Yoshika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Miyako Yoshika に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string YoshikaFullName {
            get {
                return ResourceManager.GetString("YoshikaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Youmu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Youmu {
            get {
                return ResourceManager.GetString("Youmu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Konpaku Youmu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string YoumuFullName {
            get {
                return ResourceManager.GetString("YoumuFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yukari に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Yukari {
            get {
                return ResourceManager.GetString("Yukari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yakumo Yukari に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string YukariFullName {
            get {
                return ResourceManager.GetString("YukariFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yuugi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Yuugi {
            get {
                return ResourceManager.GetString("Yuugi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hoshiguma Yuugi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string YuugiFullName {
            get {
                return ResourceManager.GetString("YuugiFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yuuka に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Yuuka {
            get {
                return ResourceManager.GetString("Yuuka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kazami Yuuka に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string YuukaFullName {
            get {
                return ResourceManager.GetString("YuukaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yuuma に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Yuuma {
            get {
                return ResourceManager.GetString("Yuuma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toutetsu Yuuma に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string YuumaFullName {
            get {
                return ResourceManager.GetString("YuumaFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yuyuko に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Yuyuko {
            get {
                return ResourceManager.GetString("Yuyuko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saigyouji Yuyuko に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string YuyukoFullName {
            get {
                return ResourceManager.GetString("YuyukoFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zanmu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Zanmu {
            get {
                return ResourceManager.GetString("Zanmu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nippaku Zanmu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZanmuFullName {
            get {
                return ResourceManager.GetString("ZanmuFullName", resourceCulture);
            }
        }
    }
}
