//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThScoreFileConverter.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThScoreFileConverter.Core.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Must not be empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentExceptionMustNotBeEmpty {
            get {
                return ResourceManager.GetString("ArgumentExceptionMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stream must be readable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentExceptionStreamMustBeReadable {
            get {
                return ResourceManager.GetString("ArgumentExceptionStreamMustBeReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrong type. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentExceptionWrongType {
            get {
                return ResourceManager.GetString("ArgumentExceptionWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} may be broken. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionFileMayBeBroken {
            get {
                return ResourceManager.GetString("InvalidDataExceptionFileMayBeBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index is out of range. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionIndexIsOutOfRange {
            get {
                return ResourceManager.GetString("InvalidDataExceptionIndexIsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index must be an integer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionIndexMustBeAnInteger {
            get {
                return ResourceManager.GetString("InvalidDataExceptionIndexMustBeAnInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of elements must not be negative. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionNumElementsMustNotBeNegative {
            get {
                return ResourceManager.GetString("InvalidDataExceptionNumElementsMustNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property {0} is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionPropertyIsInvalid {
            get {
                return ResourceManager.GetString("InvalidDataExceptionPropertyIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property {0} is out of range. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionPropertyIsOutOfRange {
            get {
                return ResourceManager.GetString("InvalidDataExceptionPropertyIsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sentinel is wrong. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionWrongSentinel {
            get {
                return ResourceManager.GetString("InvalidDataExceptionWrongSentinel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrong type. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionWrongType {
            get {
                return ResourceManager.GetString("InvalidDataExceptionWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Must be Invoked after {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidOperationExceptionMustBeInvokedAfter {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionMustBeInvokedAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encryption is not supported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotImplementedExceptionEncryptionIsNotSupported {
            get {
                return ResourceManager.GetString("NotImplementedExceptionEncryptionIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LZSS compression is not supported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotImplementedExceptionLzssCompressionIsNotSupported {
            get {
                return ResourceManager.GetString("NotImplementedExceptionLzssCompressionIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Should not reach here. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotImplementedExceptionShouldNotReachHere {
            get {
                return ResourceManager.GetString("NotImplementedExceptionShouldNotReachHere", resourceCulture);
            }
        }
    }
}
