//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThScoreFileConverter.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShotTypeNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShotTypeNames() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThScoreFileConverter.Core.Resources.ShotTypeNames", typeof(ShotTypeNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Magic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Th06_MarisaA {
            get {
                return ResourceManager.GetString("Th06.MarisaA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Magic Sign に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Th06_MarisaAFullName {
            get {
                return ResourceManager.GetString("Th06.MarisaAFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Love に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Th06_MarisaB {
            get {
                return ResourceManager.GetString("Th06.MarisaB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Love Sign に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Th06_MarisaBFullName {
            get {
                return ResourceManager.GetString("Th06.MarisaBFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spirit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Th06_ReimuA {
            get {
                return ResourceManager.GetString("Th06.ReimuA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spirit Sign に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Th06_ReimuAFullName {
            get {
                return ResourceManager.GetString("Th06.ReimuAFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dream に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Th06_ReimuB {
            get {
                return ResourceManager.GetString("Th06.ReimuB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dream Sign に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Th06_ReimuBFullName {
            get {
                return ResourceManager.GetString("Th06.ReimuBFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Magic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Th07_MarisaA {
            get {
                return ResourceManager.GetString("Th07.MarisaA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Magic Sign に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Th07_MarisaAFullName {
            get {
                return ResourceManager.GetString("Th07.MarisaAFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Love に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Th07_MarisaB {
            get {
                return ResourceManager.GetString("Th07.MarisaB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Love Sign に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Th07_MarisaBFullName {
            get {
                return ResourceManager.GetString("Th07.MarisaBFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spirit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Th07_ReimuA {
            get {
                return ResourceManager.GetString("Th07.ReimuA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spirit Sign に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Th07_ReimuAFullName {
            get {
                return ResourceManager.GetString("Th07.ReimuAFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dream に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Th07_ReimuB {
            get {
                return ResourceManager.GetString("Th07.ReimuB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dream Sign に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Th07_ReimuBFullName {
            get {
                return ResourceManager.GetString("Th07.ReimuBFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Illusion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Th07_SakuyaA {
            get {
                return ResourceManager.GetString("Th07.SakuyaA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Illusion Sign に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Th07_SakuyaAFullName {
            get {
                return ResourceManager.GetString("Th07.SakuyaAFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Th07_SakuyaB {
            get {
                return ResourceManager.GetString("Th07.SakuyaB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time Sign に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Th07_SakuyaBFullName {
            get {
                return ResourceManager.GetString("Th07.SakuyaBFullName", resourceCulture);
            }
        }
    }
}
