//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThScoreFileConverter.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThScoreFileConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About this tool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Icon ApplicationIcon {
            get {
                object obj = ResourceManager.GetObject("ApplicationIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Must not be empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentExceptionMustNotBeEmpty {
            get {
                return ResourceManager.GetString("ArgumentExceptionMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stream must be readable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentExceptionStreamMustBeReadable {
            get {
                return ResourceManager.GetString("ArgumentExceptionStreamMustBeReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrong type. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentExceptionWrongType {
            get {
                return ResourceManager.GetString("ArgumentExceptionWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .bak に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackupFileExtension {
            get {
                return ResourceManager.GetString("BackupFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *.dat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BestShotFilePattern {
            get {
                return ResourceManager.GetString("BestShotFilePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConvertedBestShotFileExtension {
            get {
                return ResourceManager.GetString("ConvertedBestShotFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} may be broken. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionFileMayBeBroken {
            get {
                return ResourceManager.GetString("InvalidDataExceptionFileMayBeBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index is out of range. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionIndexIsOutOfRange {
            get {
                return ResourceManager.GetString("InvalidDataExceptionIndexIsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index must be an integer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionIndexMustBeAnInteger {
            get {
                return ResourceManager.GetString("InvalidDataExceptionIndexMustBeAnInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of elements must not be negative. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionNumElementsMustNotBeNegative {
            get {
                return ResourceManager.GetString("InvalidDataExceptionNumElementsMustNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property {0} is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionPropertyIsInvalid {
            get {
                return ResourceManager.GetString("InvalidDataExceptionPropertyIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property {0} is out of range. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionPropertyIsOutOfRange {
            get {
                return ResourceManager.GetString("InvalidDataExceptionPropertyIsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sentinel is wrong. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionWrongSentinel {
            get {
                return ResourceManager.GetString("InvalidDataExceptionWrongSentinel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrong type. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionWrongType {
            get {
                return ResourceManager.GetString("InvalidDataExceptionWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Must be Invoked after {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidOperationExceptionMustBeInvokedAfter {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionMustBeInvokedAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Conversion finished. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageConversionFinished {
            get {
                return ResourceManager.GetString("MessageConversionFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read the score file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageFailedToReadScoreFile {
            get {
                return ResourceManager.GetString("MessageFailedToReadScoreFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the directory containing best shot files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageSelectBestShotDirectory {
            get {
                return ResourceManager.GetString("MessageSelectBestShotDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the output directory to save converted files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageSelectOutputDirectory {
            get {
                return ResourceManager.GetString("MessageSelectOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The setting file: &quot;{0}&quot; seems corrupted.
        ///Renamed to &quot;{1}&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageSettingFileIsCorrupted {
            get {
                return ResourceManager.GetString("MessageSettingFileIsCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start conversion... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStartConversion {
            get {
                return ResourceManager.GetString("MessageStartConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageTitleError {
            get {
                return ResourceManager.GetString("MessageTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageTitleWarning {
            get {
                return ResourceManager.GetString("MessageTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unhandled exception occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageUnhandledExceptionOccurred {
            get {
                return ResourceManager.GetString("MessageUnhandledExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encryption is not supported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotImplementedExceptionEncryptionIsNotSupported {
            get {
                return ResourceManager.GetString("NotImplementedExceptionEncryptionIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LZSS compression is not supported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotImplementedExceptionLzssCompressionIsNotSupported {
            get {
                return ResourceManager.GetString("NotImplementedExceptionLzssCompressionIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Should not reach here. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotImplementedExceptionShouldNotReachHere {
            get {
                return ResourceManager.GetString("NotImplementedExceptionShouldNotReachHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.colorless-sight.jp/thsfc/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProjectUrl {
            get {
                return ResourceManager.GetString("ProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Touhou score files (*.dat)|*.dat|All files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScoreFileFilter {
            get {
                return ResourceManager.GetString("ScoreFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   settings.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingFileName {
            get {
                return ResourceManager.GetString("SettingFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingWindowTitle {
            get {
                return ResourceManager.GetString("SettingWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Supported version:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SupportedVersion {
            get {
                return ResourceManager.GetString("SupportedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TemplateFileFilter {
            get {
                return ResourceManager.GetString("TemplateFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   the Embodiment of Scarlet Devil に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TH06 {
            get {
                return ResourceManager.GetString("TH06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Perfect Cherry Blossom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TH07 {
            get {
                return ResourceManager.GetString("TH07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Immaterial and Missing Power に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TH075 {
            get {
                return ResourceManager.GetString("TH075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Imperishable Night に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TH08 {
            get {
                return ResourceManager.GetString("TH08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Phantasmagoria of Flower View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TH09 {
            get {
                return ResourceManager.GetString("TH09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shoot the Bullet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TH095 {
            get {
                return ResourceManager.GetString("TH095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mountain of Faith に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TH10 {
            get {
                return ResourceManager.GetString("TH10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scarlet Weather Rhapsody に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TH105 {
            get {
                return ResourceManager.GetString("TH105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subterranean Animism に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TH11 {
            get {
                return ResourceManager.GetString("TH11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undefined Fantastic Object に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TH12 {
            get {
                return ResourceManager.GetString("TH12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Touhou Hisoutensoku に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TH123 {
            get {
                return ResourceManager.GetString("TH123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Double Spoiler に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TH125 {
            get {
                return ResourceManager.GetString("TH125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fairy Wars に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TH128 {
            get {
                return ResourceManager.GetString("TH128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ten Desires に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TH13 {
            get {
                return ResourceManager.GetString("TH13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hopeless Masquerade に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TH135 {
            get {
                return ResourceManager.GetString("TH135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Double Dealing Character に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TH14 {
            get {
                return ResourceManager.GetString("TH14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Impossible Spell Card に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TH143 {
            get {
                return ResourceManager.GetString("TH143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Urban Legend in Limbo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TH145 {
            get {
                return ResourceManager.GetString("TH145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Legacy of Lunatic Kingdom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TH15 {
            get {
                return ResourceManager.GetString("TH15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Antinomy of Common Flowers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TH155 {
            get {
                return ResourceManager.GetString("TH155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hidden Star in Four Seasons に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TH16 {
            get {
                return ResourceManager.GetString("TH16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Violet Detector に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TH165 {
            get {
                return ResourceManager.GetString("TH165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wily Beast and Weakest Creature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TH17 {
            get {
                return ResourceManager.GetString("TH17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Touhou Gouyoku Ibun に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TH175 {
            get {
                return ResourceManager.GetString("TH175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unconnected Marketeers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TH18 {
            get {
                return ResourceManager.GetString("TH18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ver. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VersionPrefix {
            get {
                return ResourceManager.GetString("VersionPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _About... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowButtonAbout {
            get {
                return ResourceManager.GetString("ViewsMainWindowButtonAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Add... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowButtonAdd {
            get {
                return ResourceManager.GetString("ViewsMainWindowButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Con_vert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowButtonConvert {
            get {
                return ResourceManager.GetString("ViewsMainWindowButtonConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Open... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowButtonOpen {
            get {
                return ResourceManager.GetString("ViewsMainWindowButtonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowButtonRemove {
            get {
                return ResourceManager.GetString("ViewsMainWindowButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   R_emove All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowButtonRemoveAll {
            get {
                return ResourceManager.GetString("ViewsMainWindowButtonRemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Setting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowButtonSetting {
            get {
                return ResourceManager.GetString("ViewsMainWindowButtonSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Hide untried card names に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowCheckBoxHideUntriedCardNames {
            get {
                return ResourceManager.GetString("ViewsMainWindowCheckBoxHideUntriedCardNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Best shot: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowLabelBestShot {
            get {
                return ResourceManager.GetString("ViewsMainWindowLabelBestShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I_mage output: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowLabelImageOutput {
            get {
                return ResourceManager.GetString("ViewsMainWindowLabelImageOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Output: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowLabelOutput {
            get {
                return ResourceManager.GetString("ViewsMainWindowLabelOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Score: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowLabelScore {
            get {
                return ResourceManager.GetString("ViewsMainWindowLabelScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Templates: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowLabelTemplates {
            get {
                return ResourceManager.GetString("ViewsMainWindowLabelTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Change... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsSettingWindowButtonChange {
            get {
                return ResourceManager.GetString("ViewsSettingWindowButtonChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   O_K に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsSettingWindowButtonOk {
            get {
                return ResourceManager.GetString("ViewsSettingWindowButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsSettingWindowButtonReset {
            get {
                return ResourceManager.GetString("ViewsSettingWindowButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Outputs numeric values with number group _separators に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsSettingWindowCheckBoxOutputNumberGroupSeparator {
            get {
                return ResourceManager.GetString("ViewsSettingWindowCheckBoxOutputNumberGroupSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Character encoding に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsSettingWindowGroupBoxCharacterEncoding {
            get {
                return ResourceManager.GetString("ViewsSettingWindowGroupBoxCharacterEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsSettingWindowGroupBoxFont {
            get {
                return ResourceManager.GetString("ViewsSettingWindowGroupBoxFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsSettingWindowGroupBoxLanguage {
            get {
                return ResourceManager.GetString("ViewsSettingWindowGroupBoxLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output formatting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsSettingWindowGroupBoxOutputFormatting {
            get {
                return ResourceManager.GetString("ViewsSettingWindowGroupBoxOutputFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   For _input file: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsSettingWindowLabelInputEncoding {
            get {
                return ResourceManager.GetString("ViewsSettingWindowLabelInputEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   For _output file: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsSettingWindowLabelOutputEncoding {
            get {
                return ResourceManager.GetString("ViewsSettingWindowLabelOutputEncoding", resourceCulture);
            }
        }
    }
}
