//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThScoreFileConverter.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThScoreFileConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Must not be empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentExceptionMustNotBeEmpty {
            get {
                return ResourceManager.GetString("ArgumentExceptionMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stream must be readable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentExceptionStreamMustBeReadable {
            get {
                return ResourceManager.GetString("ArgumentExceptionStreamMustBeReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrong type. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentExceptionWrongType {
            get {
                return ResourceManager.GetString("ArgumentExceptionWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   東方スコアファイル (*.dat)|*.dat|すべてのファイル (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fltScoreFile {
            get {
                return ResourceManager.GetString("fltScoreFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべてのファイル (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fltTemplateFile {
            get {
                return ResourceManager.GetString("fltTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index is out of range. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionIndexIsOutOfRange {
            get {
                return ResourceManager.GetString("InvalidDataExceptionIndexIsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index must be an integer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionIndexMustBeAnInteger {
            get {
                return ResourceManager.GetString("InvalidDataExceptionIndexMustBeAnInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of elements must not be negative. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionNumElementsMustNotBeNegative {
            get {
                return ResourceManager.GetString("InvalidDataExceptionNumElementsMustNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property {0} is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionPropertyIsInvalid {
            get {
                return ResourceManager.GetString("InvalidDataExceptionPropertyIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property {0} is out of range. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionPropertyIsOutOfRange {
            get {
                return ResourceManager.GetString("InvalidDataExceptionPropertyIsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sentinel is wrong. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionWrongSentinel {
            get {
                return ResourceManager.GetString("InvalidDataExceptionWrongSentinel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrong type. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionWrongType {
            get {
                return ResourceManager.GetString("InvalidDataExceptionWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TH06 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string keyTh06 {
            get {
                return ResourceManager.GetString("keyTh06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TH07 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string keyTh07 {
            get {
                return ResourceManager.GetString("keyTh07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TH075 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string keyTh075 {
            get {
                return ResourceManager.GetString("keyTh075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TH08 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string keyTh08 {
            get {
                return ResourceManager.GetString("keyTh08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TH09 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string keyTh09 {
            get {
                return ResourceManager.GetString("keyTh09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TH095 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string keyTh095 {
            get {
                return ResourceManager.GetString("keyTh095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TH10 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string keyTh10 {
            get {
                return ResourceManager.GetString("keyTh10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TH105 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string keyTh105 {
            get {
                return ResourceManager.GetString("keyTh105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TH11 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string keyTh11 {
            get {
                return ResourceManager.GetString("keyTh11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TH12 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string keyTh12 {
            get {
                return ResourceManager.GetString("keyTh12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TH123 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string keyTh123 {
            get {
                return ResourceManager.GetString("keyTh123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TH125 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string keyTh125 {
            get {
                return ResourceManager.GetString("keyTh125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TH128 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string keyTh128 {
            get {
                return ResourceManager.GetString("keyTh128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TH13 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string keyTh13 {
            get {
                return ResourceManager.GetString("keyTh13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TH135 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string keyTh135 {
            get {
                return ResourceManager.GetString("keyTh135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TH14 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string keyTh14 {
            get {
                return ResourceManager.GetString("keyTh14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TH143 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string keyTh143 {
            get {
                return ResourceManager.GetString("keyTh143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TH145 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string keyTh145 {
            get {
                return ResourceManager.GetString("keyTh145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TH15 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string keyTh15 {
            get {
                return ResourceManager.GetString("keyTh15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TH155 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string keyTh155 {
            get {
                return ResourceManager.GetString("keyTh155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TH16 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string keyTh16 {
            get {
                return ResourceManager.GetString("keyTh16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TH165 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string keyTh165 {
            get {
                return ResourceManager.GetString("keyTh165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TH17 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string keyTh17 {
            get {
                return ResourceManager.GetString("keyTh17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgEndConversion {
            get {
                return ResourceManager.GetString("msgEndConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スコアファイルの読み込みに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgErrScoreFileNotSupported {
            get {
                return ResourceManager.GetString("msgErrScoreFileNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未知の例外が発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgErrUnhandledException {
            get {
                return ResourceManager.GetString("msgErrUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定ファイル: &quot;{0}&quot; は壊れていたようです。
        ///&quot;{1}&quot; にリネームしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFmtBrokenSettingFile {
            get {
                return ResourceManager.GetString("msgFmtBrokenSettingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ベストショットファイルが保存されているディレクトリを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgSelectBestShotDirectory {
            get {
                return ResourceManager.GetString("msgSelectBestShotDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換後のファイルの出力先ディレクトリを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgSelectOutputDirectory {
            get {
                return ResourceManager.GetString("msgSelectOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力を開始します... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgStartConversion {
            get {
                return ResourceManager.GetString("msgStartConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgTitleError {
            get {
                return ResourceManager.GetString("msgTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   警告 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgTitleWarning {
            get {
                return ResourceManager.GetString("msgTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encryption is not supported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotImplementedExceptionEncryptionIsNotSupported {
            get {
                return ResourceManager.GetString("NotImplementedExceptionEncryptionIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LZSS compression is not supported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotImplementedExceptionLzssCompressionIsNotSupported {
            get {
                return ResourceManager.GetString("NotImplementedExceptionLzssCompressionIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Should not reach here. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotImplementedExceptionShouldNotReachHere {
            get {
                return ResourceManager.GetString("NotImplementedExceptionShouldNotReachHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *.dat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ptnBestShot {
            get {
                return ResourceManager.GetString("ptnBestShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .bak に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strBackupFileExtension {
            get {
                return ResourceManager.GetString("strBackupFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   bestshot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strBestShotDirectory {
            get {
                return ResourceManager.GetString("strBestShotDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strBestShotExtension {
            get {
                return ResourceManager.GetString("strBestShotExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   settings.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strSettingFile {
            get {
                return ResourceManager.GetString("strSettingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対応バージョン:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strSupportedVersions {
            get {
                return ResourceManager.GetString("strSupportedVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ver. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strVersionPrefix {
            get {
                return ResourceManager.GetString("strVersionPrefix", resourceCulture);
            }
        }
    }
}
