//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThScoreFileConverter.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThScoreFileConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About this tool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Must not be empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentExceptionMustNotBeEmpty {
            get {
                return ResourceManager.GetString("ArgumentExceptionMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stream must be readable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentExceptionStreamMustBeReadable {
            get {
                return ResourceManager.GetString("ArgumentExceptionStreamMustBeReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrong type. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ArgumentExceptionWrongType {
            get {
                return ResourceManager.GetString("ArgumentExceptionWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Touhou score files (*.dat)|*.dat|All files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fltScoreFile {
            get {
                return ResourceManager.GetString("fltScoreFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All files (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fltTemplateFile {
            get {
                return ResourceManager.GetString("fltTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index is out of range. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionIndexIsOutOfRange {
            get {
                return ResourceManager.GetString("InvalidDataExceptionIndexIsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index must be an integer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionIndexMustBeAnInteger {
            get {
                return ResourceManager.GetString("InvalidDataExceptionIndexMustBeAnInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of elements must not be negative. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionNumElementsMustNotBeNegative {
            get {
                return ResourceManager.GetString("InvalidDataExceptionNumElementsMustNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property {0} is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionPropertyIsInvalid {
            get {
                return ResourceManager.GetString("InvalidDataExceptionPropertyIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property {0} is out of range. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionPropertyIsOutOfRange {
            get {
                return ResourceManager.GetString("InvalidDataExceptionPropertyIsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sentinel is wrong. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionWrongSentinel {
            get {
                return ResourceManager.GetString("InvalidDataExceptionWrongSentinel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrong type. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDataExceptionWrongType {
            get {
                return ResourceManager.GetString("InvalidDataExceptionWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Conversion finished. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgEndConversion {
            get {
                return ResourceManager.GetString("msgEndConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read the score file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgErrScoreFileNotSupported {
            get {
                return ResourceManager.GetString("msgErrScoreFileNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unhandled exception occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgErrUnhandledException {
            get {
                return ResourceManager.GetString("msgErrUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The setting file: &quot;{0}&quot; seems corrupted.
        ///Renamed to &quot;{1}&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFmtBrokenSettingFile {
            get {
                return ResourceManager.GetString("msgFmtBrokenSettingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the directory containing bestshot files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgSelectBestShotDirectory {
            get {
                return ResourceManager.GetString("msgSelectBestShotDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the output directory to save converted files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgSelectOutputDirectory {
            get {
                return ResourceManager.GetString("msgSelectOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start conversion... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgStartConversion {
            get {
                return ResourceManager.GetString("msgStartConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgTitleError {
            get {
                return ResourceManager.GetString("msgTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgTitleWarning {
            get {
                return ResourceManager.GetString("msgTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encryption is not supported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotImplementedExceptionEncryptionIsNotSupported {
            get {
                return ResourceManager.GetString("NotImplementedExceptionEncryptionIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LZSS compression is not supported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotImplementedExceptionLzssCompressionIsNotSupported {
            get {
                return ResourceManager.GetString("NotImplementedExceptionLzssCompressionIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Should not reach here. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotImplementedExceptionShouldNotReachHere {
            get {
                return ResourceManager.GetString("NotImplementedExceptionShouldNotReachHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://www.colorless-sight.jp/thsfc/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProjectUrl {
            get {
                return ResourceManager.GetString("ProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *.dat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ptnBestShot {
            get {
                return ResourceManager.GetString("ptnBestShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingWindowTitle {
            get {
                return ResourceManager.GetString("SettingWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .bak に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strBackupFileExtension {
            get {
                return ResourceManager.GetString("strBackupFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   bestshot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strBestShotDirectory {
            get {
                return ResourceManager.GetString("strBestShotDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strBestShotExtension {
            get {
                return ResourceManager.GetString("strBestShotExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   settings.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strSettingFile {
            get {
                return ResourceManager.GetString("strSettingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Supported version:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strSupportedVersions {
            get {
                return ResourceManager.GetString("strSupportedVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ver. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string strVersionPrefix {
            get {
                return ResourceManager.GetString("strVersionPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _About... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowButtonAbout {
            get {
                return ResourceManager.GetString("ViewsMainWindowButtonAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Add... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowButtonAdd {
            get {
                return ResourceManager.GetString("ViewsMainWindowButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Con_vert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowButtonConvert {
            get {
                return ResourceManager.GetString("ViewsMainWindowButtonConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Open... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowButtonOpen {
            get {
                return ResourceManager.GetString("ViewsMainWindowButtonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowButtonRemove {
            get {
                return ResourceManager.GetString("ViewsMainWindowButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   R_emove All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowButtonRemoveAll {
            get {
                return ResourceManager.GetString("ViewsMainWindowButtonRemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Setting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowButtonSetting {
            get {
                return ResourceManager.GetString("ViewsMainWindowButtonSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Hide untried card names に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowCheckBoxHideUntriedCardNames {
            get {
                return ResourceManager.GetString("ViewsMainWindowCheckBoxHideUntriedCardNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Best shot: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowLabelBestShot {
            get {
                return ResourceManager.GetString("ViewsMainWindowLabelBestShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I_mage output: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowLabelImageOutput {
            get {
                return ResourceManager.GetString("ViewsMainWindowLabelImageOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Output: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowLabelOutput {
            get {
                return ResourceManager.GetString("ViewsMainWindowLabelOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Score: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowLabelScore {
            get {
                return ResourceManager.GetString("ViewsMainWindowLabelScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Templates: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsMainWindowLabelTemplates {
            get {
                return ResourceManager.GetString("ViewsMainWindowLabelTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Change... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsSettingWindowButtonChange {
            get {
                return ResourceManager.GetString("ViewsSettingWindowButtonChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   O_K に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsSettingWindowButtonOk {
            get {
                return ResourceManager.GetString("ViewsSettingWindowButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsSettingWindowButtonReset {
            get {
                return ResourceManager.GetString("ViewsSettingWindowButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Outputs numeric values with number group _separators に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsSettingWindowCheckBoxOutputNumberGroupSeparator {
            get {
                return ResourceManager.GetString("ViewsSettingWindowCheckBoxOutputNumberGroupSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Character encoding に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsSettingWindowGroupBoxCharacterEncoding {
            get {
                return ResourceManager.GetString("ViewsSettingWindowGroupBoxCharacterEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsSettingWindowGroupBoxFont {
            get {
                return ResourceManager.GetString("ViewsSettingWindowGroupBoxFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output formatting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsSettingWindowGroupBoxOutputFormatting {
            get {
                return ResourceManager.GetString("ViewsSettingWindowGroupBoxOutputFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   For _input file: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsSettingWindowLabelInputEncoding {
            get {
                return ResourceManager.GetString("ViewsSettingWindowLabelInputEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   For _output file: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewsSettingWindowLabelOutputEncoding {
            get {
                return ResourceManager.GetString("ViewsSettingWindowLabelOutputEncoding", resourceCulture);
            }
        }
    }
}
