//-----------------------------------------------------------------------
// <copyright file="Definitions.cs" company="None">
// Copyright (c) IIHOSHI Yoshinori.
// Licensed under the BSD-2-Clause license. See LICENSE.txt file in the project root for full license information.
// </copyright>
//-----------------------------------------------------------------------

#pragma warning disable SA1600 // Elements should be documented

using System.Collections.Generic;
using System.Linq;
using CardInfo = ThScoreFileConverter.Models.SpellCardInfo<
    ThScoreFileConverter.Models.Stage, ThScoreFileConverter.Models.Level>;

namespace ThScoreFileConverter.Models.Th17
{
    internal static class Definitions
    {
        // Thanks to thwiki.info and en.touhouwiki.net
        public static IReadOnlyDictionary<int, CardInfo> CardTable { get; } = new List<CardInfo>()
        {
#pragma warning disable SA1008 // Opening parenthesis should be spaced correctly
            new CardInfo(  1, "石符「ストーンウッズ」",               Stage.One,   Level.Easy),
            new CardInfo(  2, "石符「ストーンウッズ」",               Stage.One,   Level.Normal),
            new CardInfo(  3, "石符「ストーンコニファー」",           Stage.One,   Level.Hard),
            new CardInfo(  4, "石符「ストーンコニファー」",           Stage.One,   Level.Lunatic),
            new CardInfo(  5, "石符「チルドレンズリンボ」",           Stage.One,   Level.Easy),
            new CardInfo(  6, "石符「チルドレンズリンボ」",           Stage.One,   Level.Normal),
            new CardInfo(  7, "石符「アダルトチルドレンズリンボ」",   Stage.One,   Level.Hard),
            new CardInfo(  8, "石符「アダルトチルドレンズリンボ」",   Stage.One,   Level.Lunatic),
            new CardInfo(  9, "石符「ストーンベイビー」",             Stage.Two,   Level.Easy),
            new CardInfo( 10, "石符「ストーンベイビー」",             Stage.Two,   Level.Normal),
            new CardInfo( 11, "石符「ヘビーストーンベイビー」",       Stage.Two,   Level.Hard),
            new CardInfo( 12, "石符「ヘビーストーンベイビー」",       Stage.Two,   Level.Lunatic),
            new CardInfo( 13, "溺符「三途の淪溺」",                   Stage.Two,   Level.Easy),
            new CardInfo( 14, "溺符「三途の淪溺」",                   Stage.Two,   Level.Normal),
            new CardInfo( 15, "溺符「三途の淪溺」",                   Stage.Two,   Level.Hard),
            new CardInfo( 16, "溺符「三途の淪溺」",                   Stage.Two,   Level.Lunatic),
            new CardInfo( 17, "鬼符「デーモンシージ」",               Stage.Two,   Level.Easy),
            new CardInfo( 18, "鬼符「デーモンシージ」",               Stage.Two,   Level.Normal),
            new CardInfo( 19, "鬼符「ハングリーデーモンシージ」",     Stage.Two,   Level.Hard),
            new CardInfo( 20, "鬼符「ハングリーデーモンシージ」",     Stage.Two,   Level.Lunatic),
            new CardInfo( 21, "水符「水配りの試練」",                 Stage.Three, Level.Easy),
            new CardInfo( 22, "水符「水配りの試練」",                 Stage.Three, Level.Normal),
            new CardInfo( 23, "水符「水配りの上級試煉」",             Stage.Three, Level.Hard),
            new CardInfo( 24, "水符「水配りの極級試煉」",             Stage.Three, Level.Lunatic),
            new CardInfo( 25, "光符「見渡しの試練」",                 Stage.Three, Level.Easy),
            new CardInfo( 26, "光符「見渡しの試練」",                 Stage.Three, Level.Normal),
            new CardInfo( 27, "光符「見渡しの上級試煉」",             Stage.Three, Level.Hard),
            new CardInfo( 28, "光符「見渡しの極級試煉」",             Stage.Three, Level.Lunatic),
            new CardInfo( 29, "鬼符「鬼渡の試練」",                   Stage.Three, Level.Easy),
            new CardInfo( 30, "鬼符「鬼渡の試練」",                   Stage.Three, Level.Normal),
            new CardInfo( 31, "鬼符「鬼渡の上級試煉」",               Stage.Three, Level.Hard),
            new CardInfo( 32, "鬼符「鬼渡の獄級試煉」",               Stage.Three, Level.Lunatic),
            new CardInfo( 33, "亀符「亀甲地獄」",                     Stage.Four,  Level.Easy),
            new CardInfo( 34, "亀符「亀甲地獄」",                     Stage.Four,  Level.Normal),
            new CardInfo( 35, "亀符「亀甲地獄」",                     Stage.Four,  Level.Hard),
            new CardInfo( 36, "亀符「亀甲地獄」",                     Stage.Four,  Level.Lunatic),
            new CardInfo( 37, "鬼符「搦手の畜生」",                   Stage.Four,  Level.Easy),
            new CardInfo( 38, "鬼符「搦手の畜生」",                   Stage.Four,  Level.Normal),
            new CardInfo( 39, "鬼符「搦手の犬畜生」",                 Stage.Four,  Level.Hard),
            new CardInfo( 40, "鬼符「搦手の鬼畜生」",                 Stage.Four,  Level.Lunatic),
            new CardInfo( 41, "龍符「龍紋弾」",                       Stage.Four,  Level.Easy),
            new CardInfo( 42, "龍符「龍紋弾」",                       Stage.Four,  Level.Normal),
            new CardInfo( 43, "龍符「龍紋弾」",                       Stage.Four,  Level.Hard),
            new CardInfo( 44, "龍符「龍紋弾」",                       Stage.Four,  Level.Lunatic),
            new CardInfo( 45, "埴輪「弓兵埴輪」",                     Stage.Five,  Level.Easy),
            new CardInfo( 46, "埴輪「弓兵埴輪」",                     Stage.Five,  Level.Normal),
            new CardInfo( 47, "埴輪「熟練弓兵埴輪」",                 Stage.Five,  Level.Hard),
            new CardInfo( 48, "埴輪「熟練弓兵埴輪」",                 Stage.Five,  Level.Lunatic),
            new CardInfo( 49, "埴輪「剣士埴輪」",                     Stage.Five,  Level.Easy),
            new CardInfo( 50, "埴輪「剣士埴輪」",                     Stage.Five,  Level.Normal),
            new CardInfo( 51, "埴輪「熟練剣士埴輪」",                 Stage.Five,  Level.Hard),
            new CardInfo( 52, "埴輪「熟練剣士埴輪」",                 Stage.Five,  Level.Lunatic),
            new CardInfo( 53, "埴輪「騎馬兵埴輪」",                   Stage.Five,  Level.Easy),
            new CardInfo( 54, "埴輪「騎馬兵埴輪」",                   Stage.Five,  Level.Normal),
            new CardInfo( 55, "埴輪「熟練騎馬兵埴輪」",               Stage.Five,  Level.Hard),
            new CardInfo( 56, "埴輪「熟練騎馬兵埴輪」",               Stage.Five,  Level.Lunatic),
            new CardInfo( 57, "埴輪「がらんどうの無尽兵団」",         Stage.Five,  Level.Easy),
            new CardInfo( 58, "埴輪「がらんどうの無尽兵団」",         Stage.Five,  Level.Normal),
            new CardInfo( 59, "埴輪「不敗の無尽兵団」",               Stage.Five,  Level.Hard),
            new CardInfo( 60, "埴輪「不敗の無尽兵団」",               Stage.Five,  Level.Lunatic),
            new CardInfo( 61, "方形「方形造形術」",                   Stage.Six,   Level.Easy),
            new CardInfo( 62, "方形「方形造形術」",                   Stage.Six,   Level.Normal),
            new CardInfo( 63, "方形「スクエアクリーチャー」",         Stage.Six,   Level.Hard),
            new CardInfo( 64, "方形「スクエアクリーチャー」",         Stage.Six,   Level.Lunatic),
            new CardInfo( 65, "円形「真円造形術」",                   Stage.Six,   Level.Easy),
            new CardInfo( 66, "円形「真円造形術」",                   Stage.Six,   Level.Normal),
            new CardInfo( 67, "円形「サークルクリーチャー」",         Stage.Six,   Level.Hard),
            new CardInfo( 68, "円形「サークルクリーチャー」",         Stage.Six,   Level.Lunatic),
            new CardInfo( 69, "線形「線形造形術」",                   Stage.Six,   Level.Easy),
            new CardInfo( 70, "線形「線形造形術」",                   Stage.Six,   Level.Normal),
            new CardInfo( 71, "線形「リニアクリーチャー」",           Stage.Six,   Level.Hard),
            new CardInfo( 72, "線形「リニアクリーチャー」",           Stage.Six,   Level.Lunatic),
            new CardInfo( 73, "埴輪「偶像人馬造形術」",               Stage.Six,   Level.Easy),
            new CardInfo( 74, "埴輪「偶像人馬造形術」",               Stage.Six,   Level.Normal),
            new CardInfo( 75, "埴輪「アイドルクリーチャー」",         Stage.Six,   Level.Hard),
            new CardInfo( 76, "埴輪「アイドルクリーチャー」",         Stage.Six,   Level.Lunatic),
            new CardInfo( 77, "「鬼形造形術」",                       Stage.Six,   Level.Easy),
            new CardInfo( 78, "「鬼形造形術」",                       Stage.Six,   Level.Normal),
            new CardInfo( 79, "「鬼形造形術」",                       Stage.Six,   Level.Hard),
            new CardInfo( 80, "「鬼形造形術」",                       Stage.Six,   Level.Lunatic),
            new CardInfo( 81, "「ジオメトリッククリーチャー」",       Stage.Six,   Level.Easy),
            new CardInfo( 82, "「ジオメトリッククリーチャー」",       Stage.Six,   Level.Normal),
            new CardInfo( 83, "「ジオメトリッククリーチャー」",       Stage.Six,   Level.Hard),
            new CardInfo( 84, "「ジオメトリッククリーチャー」",       Stage.Six,   Level.Lunatic),
            new CardInfo( 85, "「イドラディアボルス」",               Stage.Six,   Level.Easy),
            new CardInfo( 86, "「イドラディアボルス」",               Stage.Six,   Level.Normal),
            new CardInfo( 87, "「イドラディアボルス」",               Stage.Six,   Level.Hard),
            new CardInfo( 88, "「イドラディアボルス」",               Stage.Six,   Level.Lunatic),
            new CardInfo( 89, "血戦「血の分水嶺」",                   Stage.Extra, Level.Extra),
            new CardInfo( 90, "血戦「獄界視線」",                     Stage.Extra, Level.Extra),
            new CardInfo( 91, "血戦「全霊鬼渡り」",                   Stage.Extra, Level.Extra),
            new CardInfo( 92, "勁疾技「スリリングショット」",         Stage.Extra, Level.Extra),
            new CardInfo( 93, "勁疾技「ライトニングネイ」",           Stage.Extra, Level.Extra),
            new CardInfo( 94, "勁疾技「デンスクラウド」",             Stage.Extra, Level.Extra),
            new CardInfo( 95, "勁疾技「ビーストエピデミシティ」",     Stage.Extra, Level.Extra),
            new CardInfo( 96, "勁疾技「トライアングルチェイス」",     Stage.Extra, Level.Extra),
            new CardInfo( 97, "勁疾技「ブラックペガサス流星弾」",     Stage.Extra, Level.Extra),
            new CardInfo( 98, "勁疾技「マッスルエクスプロージョン」", Stage.Extra, Level.Extra),
            new CardInfo( 99, "「フォロミーアンアフライド」",         Stage.Extra, Level.Extra),
            new CardInfo(100, "「鬼形のホイポロイ」",                 Stage.Extra, Level.Extra),
            new CardInfo(101, "「鬼畜生の所業」",                     Stage.Extra, Level.Extra),
#pragma warning restore SA1008 // Opening parenthesis should be spaced correctly
        }.ToDictionary(card => card.Id);

        // Thanks to en.touhouwiki.net
        public static IReadOnlyList<string> Achievements { get; } = new List<string>
        {
            "霊夢（オオカミ霊）クリア",
            "霊夢（カワウソ霊）クリア",
            "霊夢（オオワシ霊）クリア",
            "魔理沙（オオカミ霊）クリア",
            "魔理沙（カワウソ霊）クリア",
            "魔理沙（オオワシ霊）クリア",
            "妖夢（オオカミ霊）クリア",
            "妖夢（カワウソ霊）クリア",
            "妖夢（オオワシ霊）クリア",
            "霊夢バッドエンド",
            "魔理沙BADクリア",
            "妖夢BADクリア",
            "霊夢（オオカミ霊）EXクリア",
            "霊夢（カワウソ霊）EXクリア",
            "霊夢（オオワシ霊）EXクリア",
            "魔理沙（オオカミ霊）EXクリア",
            "魔理沙（カワウソ霊）EXクリア",
            "魔理沙（オオワシ霊）EXクリア",
            "妖夢（オオカミ霊）EXクリア",
            "妖夢（カワウソ霊）EXクリア",
            "妖夢（オオワシ霊）EXクリア",
            "イージークリア",
            "ノーマルクリア",
            "ハードクリア",
            "ルナティッククリア",
            "イージーノーコンクリア",
            "ノーマルノーコンクリア",
            "ハードNCクリア",
            "ルナティックNCクリア",
            "パーフェクトクリア",
            "畜生界の破壊神",
            "畜生を蹂躙する者",
            "スペルカードコレクター",
            "クラゲ大好き",
            "そうだ牛乳を飲もう",
            "生まれたてのピヨちゃん",
            "のんびりコツコツと",
            "おーいハニマルさん",
            "土の馬",
            "ひよこが三匹",
        };

        public static string FormatPrefix { get; } = "%T17";
    }
}
