//-----------------------------------------------------------------------
// <copyright file="Definitions.cs" company="None">
// Copyright (c) IIHOSHI Yoshinori.
// Licensed under the BSD-2-Clause license. See LICENSE.txt file in the project root for full license information.
// </copyright>
//-----------------------------------------------------------------------

using System.Collections.Generic;

namespace ThScoreFileConverter.Core.Models.Th125;

/// <summary>
/// Provides several DS specific definitions.
/// </summary>
public static class Definitions
{
    /// <summary>
    /// Gets the dictionary of DS spell cards.
    /// Thanks to thwiki.info.
    /// </summary>
    public static IReadOnlyDictionary<(Level Level, int Scene), (Enemy Enemy, string Card)> SpellCards { get; } =
        new Dictionary<(Level, int), (Enemy, string)>
        {
            { (Level.One,     1), (Enemy.Minoriko,  string.Empty) },
            { (Level.One,     2), (Enemy.Minoriko,  string.Empty) },
            { (Level.One,     3), (Enemy.Shizuha,   "秋符「フォーリンブラスト」") },
            { (Level.One,     4), (Enemy.Minoriko,  "実符「ウォームカラーハーヴェスト」") },
            { (Level.One,     5), (Enemy.Shizuha,   "枯道「ロストウィンドロウ」") },
            { (Level.One,     6), (Enemy.Minoriko,  "焼芋「スイートポテトルーム」") },
            { (Level.Two,     1), (Enemy.Parsee,    string.Empty) },
            { (Level.Two,     2), (Enemy.Hina,      string.Empty) },
            { (Level.Two,     3), (Enemy.Parsee,    "嫉妬「ジェラシーボンバー」") },
            { (Level.Two,     4), (Enemy.Hina,      "厄野「禊川の堆積」") },
            { (Level.Two,     5), (Enemy.Parsee,    "怨み念法「積怨返し」") },
            { (Level.Two,     6), (Enemy.Hina,      "災禍「呪いの雛人形」") },
            { (Level.Three,   1), (Enemy.Yamame,    string.Empty) },
            { (Level.Three,   2), (Enemy.Kogasa,    "傘符「一本足ピッチャー返し」") },
            { (Level.Three,   3), (Enemy.Kisume,    "釣瓶「飛んで井の中」") },
            { (Level.Three,   4), (Enemy.Yamame,    "細綱「カンダタロープ」") },
            { (Level.Three,   5), (Enemy.Kogasa,    "虹符「オーバー・ザ・レインボー」") },
            { (Level.Three,   6), (Enemy.Kisume,    "釣瓶「ウェルディストラクター」") },
            { (Level.Three,   7), (Enemy.Yamame,    "毒符「樺黄小町」") },
            { (Level.Three,   8), (Enemy.Kogasa,    "傘符「細雪の過客」") },
            { (Level.Four,    1), (Enemy.Nitori,    string.Empty) },
            { (Level.Four,    2), (Enemy.Momiji,    string.Empty) },
            { (Level.Four,    3), (Enemy.Nitori,    "水符「ウォーターカーペット」") },
            { (Level.Four,    4), (Enemy.Momiji,    "狗符「レイビーズバイト」") },
            { (Level.Four,    5), (Enemy.Nitori,    "河符「ディバイディングエッジ」") },
            { (Level.Four,    6), (Enemy.Momiji,    "山窩「エクスペリーズカナン」") },
            { (Level.Four,    7), (Enemy.Nitori,    "河童「乾燥尻子玉」") },
            { (Level.Five,    1), (Enemy.Ichirin,   string.Empty) },
            { (Level.Five,    2), (Enemy.Minamitsu, string.Empty) },
            { (Level.Five,    3), (Enemy.Ichirin,   "拳骨「天空鉄槌落とし」") },
            { (Level.Five,    4), (Enemy.Minamitsu, "錨符「幽霊船長期停泊」") },
            { (Level.Five,    5), (Enemy.Ichirin,   "稲妻「帯電入道」") },
            { (Level.Five,    6), (Enemy.Minamitsu, "浸水「船底のヴィーナス」") },
            { (Level.Five,    7), (Enemy.Ichirin,   "鉄拳「入道にょき」") },
            { (Level.Five,    8), (Enemy.Minamitsu, "「ディープシンカー」") },
            { (Level.Six,     1), (Enemy.Yuugi,     string.Empty) },
            { (Level.Six,     2), (Enemy.Suika,     string.Empty) },
            { (Level.Six,     3), (Enemy.Yuugi,     "光鬼「金剛螺旋」") },
            { (Level.Six,     4), (Enemy.Suika,     "鬼符「豆粒大の針地獄」") },
            { (Level.Six,     5), (Enemy.Yuugi,     "鬼符「鬼気狂瀾」") },
            { (Level.Six,     6), (Enemy.Suika,     "地獄「煉獄吐息」") },
            { (Level.Six,     7), (Enemy.Yuugi,     "鬼声「壊滅の咆哮」") },
            { (Level.Six,     8), (Enemy.Suika,     "鬼符「ミッシングパワー」") },
            { (Level.Seven,   1), (Enemy.Shou,      string.Empty) },
            { (Level.Seven,   2), (Enemy.Nazrin,    string.Empty) },
            { (Level.Seven,   3), (Enemy.Shou,      "寅符「ハングリータイガー」") },
            { (Level.Seven,   4), (Enemy.Nazrin,    "棒符「ナズーリンロッド」") },
            { (Level.Seven,   5), (Enemy.Shou,      "天符「焦土曼荼羅」") },
            { (Level.Seven,   6), (Enemy.Nazrin,    "財宝「ゴールドラッシュ」") },
            { (Level.Seven,   7), (Enemy.Shou,      "宝符「黄金の震眩」") },
            { (Level.Eight,   1), (Enemy.Rin,       string.Empty) },
            { (Level.Eight,   2), (Enemy.Utsuho,    "熔解「メルティングホワイト」") },
            { (Level.Eight,   3), (Enemy.Rin,       "死符「ゴーストタウン」") },
            { (Level.Eight,   4), (Enemy.Utsuho,    "巨星「レッドジャイアント」") },
            { (Level.Eight,   5), (Enemy.Rin,       "「死体繁華街」") },
            { (Level.Eight,   6), (Enemy.Utsuho,    "星符「巨星墜つ」") },
            { (Level.Eight,   7), (Enemy.Rin,       "酔歩「キャットランダムウォーク」") },
            { (Level.Eight,   8), (Enemy.Utsuho,    "七星「セプテントリオン」") },
            { (Level.Nine,    1), (Enemy.Satori,    string.Empty) },
            { (Level.Nine,    2), (Enemy.Koishi,    "心符「没我の愛」") },
            { (Level.Nine,    3), (Enemy.Satori,    "脳符「ブレインフィンガープリント」") },
            { (Level.Nine,    4), (Enemy.Koishi,    "記憶「ＤＮＡの瑕」") },
            { (Level.Nine,    5), (Enemy.Satori,    "心花「カメラシャイローズ」") },
            { (Level.Nine,    6), (Enemy.Koishi,    "「胎児の夢」") },
            { (Level.Nine,    7), (Enemy.Satori,    "想起「うろおぼえの金閣寺」") },
            { (Level.Nine,    8), (Enemy.Koishi,    "「ローズ地獄」") },
            { (Level.Ten,     1), (Enemy.Tenshi,    "気性「勇気凛々の剣」") },
            { (Level.Ten,     2), (Enemy.Iku,       "雷符「ライトニングフィッシュ」") },
            { (Level.Ten,     3), (Enemy.Tenshi,    "地震「避難険路」") },
            { (Level.Ten,     4), (Enemy.Iku,       "珠符「五爪龍の珠」") },
            { (Level.Ten,     5), (Enemy.Tenshi,    "要石「カナメファンネル」") },
            { (Level.Ten,     6), (Enemy.Iku,       "龍宮「タイヤヒラメダンス」") },
            { (Level.Ten,     7), (Enemy.Tenshi,    "「全人類の緋想天」") },
            { (Level.Ten,     8), (Enemy.Iku,       "龍魚「龍宮の使い遊泳弾」") },
            { (Level.Eleven,  1), (Enemy.Kanako,    string.Empty) },
            { (Level.Eleven,  2), (Enemy.Suwako,    "神桜「湛えの桜吹雪」") },
            { (Level.Eleven,  3), (Enemy.Kanako,    "蛇符「グラウンドサーペント」") },
            { (Level.Eleven,  4), (Enemy.Suwako,    "姫川「プリンセスジェイドグリーン」") },
            { (Level.Eleven,  5), (Enemy.Kanako,    "御柱「メテオリックオンバシラ」") },
            { (Level.Eleven,  6), (Enemy.Suwako,    "鉄輪「ミシカルリング」") },
            { (Level.Eleven,  7), (Enemy.Kanako,    "儚道「御神渡りクロス」") },
            { (Level.Eleven,  8), (Enemy.Suwako,    "土着神「御射軍神さま」") },
            { (Level.Twelve,  1), (Enemy.Byakuren,  string.Empty) },
            { (Level.Twelve,  2), (Enemy.Nue,       "正体不明「紫鏡」") },
            { (Level.Twelve,  3), (Enemy.Byakuren,  "「遊行聖」") },
            { (Level.Twelve,  4), (Enemy.Nue,       "正体不明「赤マント青マント」") },
            { (Level.Twelve,  5), (Enemy.Byakuren,  "習合「垂迹大日如来」") },
            { (Level.Twelve,  6), (Enemy.Nue,       "正体不明「厠の花子さん」") },
            { (Level.Twelve,  7), (Enemy.Byakuren,  "「スターソードの護法」") },
            { (Level.Twelve,  8), (Enemy.Nue,       "「遊星よりの弾幕Ｘ」") },
            { (Level.Extra,   1), (Enemy.Reimu,     "お札「新聞拡張団調伏」") },
            { (Level.Extra,   2), (Enemy.Marisa,    "星符「オールトクラウド」") },
            { (Level.Extra,   3), (Enemy.Sanae,     "奇跡「弘安の神風」") },
            { (Level.Extra,   4), (Enemy.Reimu,     "結界「パパラッチ撃退結界」") },
            { (Level.Extra,   5), (Enemy.Marisa,    "天儀「オーレリーズソーラーシステム」") },
            { (Level.Extra,   6), (Enemy.Sanae,     "蛙符「手管の蝦蟇」") },
            { (Level.Extra,   7), (Enemy.Reimu,     "夢符「夢想亜空穴」") },
            { (Level.Extra,   8), (Enemy.Marisa,    "彗星「ブレイジングスター」") },
            { (Level.Extra,   9), (Enemy.Sanae,     "妖怪退治「妖力スポイラー」") },
            { (Level.Spoiler, 1), (Enemy.Hatate,    string.Empty) },
            { (Level.Spoiler, 2), (Enemy.Hatate,    "取材「姫海棠はたての練習取材」") },
            { (Level.Spoiler, 3), (Enemy.Hatate,    "連写「ラピッドショット」") },
            { (Level.Spoiler, 4), (Enemy.Hatate,    "遠眼「天狗サイコグラフィ」") },
            { (Level.Spoiler, 5), (Enemy.Aya,       string.Empty) },
            { (Level.Spoiler, 6), (Enemy.Aya,       "取材「射命丸文の圧迫取材」") },
            { (Level.Spoiler, 7), (Enemy.Aya,       "望遠「キャンディッドショット」") },
            { (Level.Spoiler, 8), (Enemy.Aya,       "速写「ファストショット」") },
            { (Level.Spoiler, 9), (Enemy.Aya,       "「幻想風靡」") },
        };
}
